### ISSUE TITLE
MERN/Login/profile/upload picture 

### ISSUE THREAD

**Issue by kevinlizh1992** [yida-li/SOEN341#11]
-Each member will learn MERN stack

-Create front/back/UI for login page (account creation vs. log in with existing account). User chose between ability to register or sign into existing account. 

-Create user profile page when user logs in. Once logged in, user should be able to to see their name buttons: Edit (profile description), Friends, + (plus button) to add photos.

-Clicking on the + button should bring the account owner to another page where they can upload a picture. Once uploaded, user will be redirected to their profile page.

_Originally posted by @kevinlizh1992 in https://github.com/yida-li/SOEN341/issues/5#issuecomment-579876512_

**Comment by Alex-DSJ** [comment]
new specification for this issue has been posted and this issue will be closed.
and actually, all sub-issued mentioned here has been solved
