### ISSUE TITLE
Add comment system under pictures

### ISSUE THREAD

**Issue by kevinlizh1992** [yida-li/SOEN341#15]
- [x] Under each posted picture, there shall be an UI that displays a clickable comment button.
- [x] Clicking on this comment button will reveal all comments previously made.
- [x] Users shall then be able to comment using provided text space.
- [x] User's comment will appear in chronological order, that is, newer comments figure at the top.
- [x] everyone should be able to comment on anyone's pictures.
- [x] comments on others should not be allowed

**Comment by kevinlizh1992** [comment]
Currently attempted to incorporate comment via learning on Udemy, issue with database, will push this into milestone 4

**Comment by Alex-DSJ** [comment]
sub issues been created, so close this one.

**Comment by Alex-DSJ** [comment]
sub issues been created, close this one.
