### ISSUE TITLE
Implement and link search bar to database, and ability to follow users found

### ISSUE THREAD

**Issue by kevinlizh1992** [yida-li/SOEN341#17]
-User shall have access to search bar in profile page (and other user page if possible)
-Search bar allows user to find other users.
-Searching user by username will directly link to their profile if they exist

**Comment by successsb89** [comment]
Sine we have decided to focus more on newfeed and like for our additional core features, this issue is close now.

**Comment by Alex-DSJ** [comment]
since we have some idea about how to impelment this function, we decided to do this function again, reopen the issue

**Comment by successsb89** [comment]
now the search bar works as showing related users one that try to search, however, it does not have funtionality of following users.

**Comment by kennguyen0303** [comment]
this is done. All three key points @kevinlizh1992  mentioned above are finished. 

Can be closed now

**Comment by Alex-DSJ** [comment]
ok, I will close it, Thank you!
