### ISSUE TITLE
Create home/profile page button in every page

### ISSUE THREAD

**Issue by kevinlizh1992** [yida-li/SOEN341#19]
User shall be able to return to profile at any point while using the webapp

**Comment by successsb89** [comment]
done

**Comment by Alex-DSJ** [comment]
[Acceptance Test](https://docs.google.com/spreadsheets/d/1CZK1ZZp62FcBFFwwg0ovlHvdOsHcdHgSov8aXYTdMAY/edit?usp=sharing) in row 22
