### ISSUE TITLE
non-functional specification of picture-uploading page for core feature 1 #5

### ISSUE THREAD

**Issue by Alex-DSJ** [yida-li/SOEN341#27]
non-functional specifications for picture-uploading page of core feature 1 #5 
after finish all, go #5 and **check the non-functional specification checkbox of picture-uploading page.**

- [x] the posted picture will be shown in the user's profile;
- [ ] other users should see these posted picture only by entering the user's profile;

**Comment by successsb89** [comment]
posted pictures will be shown on the user's profile

**Comment by Alex-DSJ** [comment]
[Acceptance Test](https://docs.google.com/spreadsheets/d/1CZK1ZZp62FcBFFwwg0ovlHvdOsHcdHgSov8aXYTdMAY/edit?usp=sharing) in row 7
