### ISSUE TITLE
Image Display on profile page

### ISSUE THREAD

**Issue by Alex-DSJ** [yida-li/SOEN341#35]
The user's picture should be displayed on the top left of the user's profile page.
This issure comes from #26

**Comment by successsb89** [comment]
done

**Comment by Alex-DSJ** [comment]
[Acceptance Test](https://docs.google.com/spreadsheets/d/1CZK1ZZp62FcBFFwwg0ovlHvdOsHcdHgSov8aXYTdMAY/edit?usp=sharing) in row 7
