### ISSUE TITLE
Posted pictures and descriptions on the profile page

### ISSUE THREAD

**Issue by Alex-DSJ** [yida-li/SOEN341#39]
All posted pictures and descriptions should displayed below the bottom line of the user's image;
The description of the picture should displayed above the picture;
All descriptions and pictures should displayed in reverse chronological order, which means the more lastest picture, the higher.

This issue comes from #26

**Comment by successsb89** [comment]
done

**Comment by Alex-DSJ** [comment]
[Acceptance Test](https://docs.google.com/spreadsheets/d/1CZK1ZZp62FcBFFwwg0ovlHvdOsHcdHgSov8aXYTdMAY/edit?usp=sharing) in row 7
