### ISSUE TITLE
"Comment" button on the profile page

### ISSUE THREAD

**Issue by Alex-DSJ** [yida-li/SOEN341#40]
There should be only one "Comment" button for each picture;
After clicking "Comment" button, all comments of the picture should be shown;
After clicking "Comment" button, a text input field should shown and allow the user to input comment here;
After clicking "Comment" button, a "Submit" button should shown below the text input field to submit the comment to the data base and shown below the picture later on;
The comments should displayed in reverse chronological order.

This issue comes from #26

**Comment by kennguyen0303** [comment]
#40 
I am struggling with the searching using filter. Please help me.

I need to set up a search using picture ID for the component PicturePage to obtain the frontendPath to display a picture

**Comment by successsb89** [comment]
comment part has been implemented to back-end side respect with requirements. It will resume when front-end start in Sprint4.

**Comment by kevinlizh1992** [comment]
Comment section done, it opens a dialog box that displays user comment section and submit button to submit your comment. Latest comment figures at the top of the list. Works with DB.
