### ISSUE TITLE
"Like" button on other user's profile

### ISSUE THREAD

**Issue by Alex-DSJ** [yida-li/SOEN341#41]
When a user visit other's profile, the "Friends" drop-down menu should be replaced by a "Like" button;
On clicking this button, the user who visiting this profile will add the user of this profile to his/her "Friends" list and shown on his/her "Friend" drop-down menu.

This issue comes from #26

**Comment by successsb89** [comment]
Since this additional core feature has been implemented for the backend side and only detail part of front end is remained with further design matter, this issue will resume in sprint 4.
