### ISSUE TITLE
Additional Feature: Notification

### ISSUE THREAD

**Issue by Alex-DSJ** [yida-li/SOEN341#46]
This is an additional feature beside those three core features.
This issue is to summary specifications for "Notification" feature, will be closed after these specifications assigned to new issues.

The user should get notification when someone comments on his/her posted picture.
The user should get notification when his/her following friends posted new pictures.
The notification should have the information of "who has done what to whom", but don't have to show the detailed information. For example: "Kevin has commented on your posted picture"

**Comment by yida-li** [comment]
The idea for notification : Boolean variable associated with each user, can be triggered by multiple scenarios.
Initially set to false, triggered(set true) if user is followed, user's picture is commented, user's comment is replied

**Comment by Alex-DSJ** [comment]
did the customer has require the function of "being able to reply a comment" @yida-li

**Comment by Alex-DSJ** [comment]
related sub-issues have been created
