### ISSUE TITLE
Additional feature: News Feed

### ISSUE THREAD

**Issue by Alex-DSJ** [yida-li/SOEN341#48]
This issue is for the discussion and summerization of "News feed" feature.
We will create other issues according to our discussion result and close this one.

**Comment by Alex-DSJ** [comment]
the format of the "News feed", I think we can simply keep the format of the posted pictures: description --> picture --> comment(s)

**Comment by yida-li** [comment]
> what should we display in "News feed", do we have to show others' comments about the pictures too, or just focus on the interaction with the user. For me, I wanna stay focus on the communcation of the user and me, what about you guys?

So newsfeed will fetch the latest picture that a user has submitted?

**Comment by kevinlizh1992** [comment]
We need to discuss about implementing the vibez like system instead, which is what the app is named after

**Comment by Alex-DSJ** [comment]
this is a discussion board for the newsfeed functionality

**Comment by kennguyen0303** [comment]
newsfeed is now showing all the posts. Since the following function is not complete yet. In the future, once the following function is finished, the newsfeed will only show the posts from whom the user follows

**Comment by Alex-DSJ** [comment]
ok, since the specifications of this function are clear, this "discussion board" will be close.
