### ISSUE TITLE
additional feature: liking system

### ISSUE THREAD

**Issue by kevinlizh1992** [yida-li/SOEN341#49]
other users can "like" someone's vibe, and the user been liked should revceive a notification.
once click the "like" button, the button should changed into an "unlike" button, the user can retrieve the "like" by clicking the unlike.

**Comment by kevinlizh1992** [comment]
How it goes:
1. user looks at pictures
2. user shall see number of likes and comments
3. clicking on number of likes will expand the like section, revealing all reactions made so far
4. hovering over each reaction now will indicate exact number of people who also reacted the same way, (perhaps add who liked)
5. only main default "like" should be public
6. Others custom reactions are anonymous

**Comment by kennguyen0303** [comment]
This feature is ready to use. Can be closed now

**Comment by successsb89** [comment]
Since like functionality of back-end has been implemented, this issue is open for further CSS part for like system @kevinlizh1992

**Comment by kevinlizh1992** [comment]
> Since like functionality of back-end has been implemented, this issue is open for further CSS part for like system @kevinlizh1992

Like system done and incorporated, CSS works, buttons dynamically change to show liked or unliked.

**Comment by Alex-DSJ** [comment]
[Acceptance Test](https://docs.google.com/spreadsheets/d/1CZK1ZZp62FcBFFwwg0ovlHvdOsHcdHgSov8aXYTdMAY/edit?usp=sharing) in row 20
