### ISSUE TITLE
core feature 1: posting picture

### ISSUE THREAD

**Issue by Alex-DSJ** [yida-li/SOEN341#5]
one of the core feature required by our customer is that user can post their pictures on the application.

**Comment by successsb89** [comment]
user interface is needed to start the posting process. i.e. button that brings you to the page where you need to upload picture

**Comment by Alex-DSJ** [comment]
good, and the picture should be posted on user's profile as well as the news feed?

**Comment by kevinlizh1992** [comment]
At the picture posting page, there needs to be UI/backend to go fetch a picture file on your computer since it's a webapp, it could be a simple attach file style UI for sending emails

**Comment by kevinlizh1992** [comment]
Once upload completes, there should be a hyperlink/image to redirect you to your own page or to news feed

**Comment by kevinlizh1992** [comment]
-Each member will learn MERN stack

-Create front/back/UI for login page (account creation vs. log in with existing account)

-Create user profile page when user logs in

-Ability to post picture from computer

**Comment by Alex-DSJ** [comment]
the specification for login page:

- [ ] users should be prompted to enter username and password;
- [ ] sign up and sign in should integrated into this one page, with two buttons;
- [ ] login information should be stored in MongoDB;
- [ ] verification should be carried by frontend/backend(TBD);
- [ ] after login successfully(use a correct pair of username and password, or sign up successfully), user should be redirect to the user's profile page;
- [ ] related CSS;

**Comment by Alex-DSJ** [comment]
the specification for profile page:

- [ ] the page should display the user image on the top left and the user name on the top right beside the image
- [ ] below the user name, there should be a drop-down menu contains all following users, and a "+" button to redirect to the picture uploading page;
- [ ] the drop-down menu and the "+" button should align with the bottom of the user's image;
- [ ] below should be the posted pics of the user in reverse chronological order, with the desciption above and comments below, commnets will also displayed in reverse chronological order.
- [ ] related CSS

**Comment by Alex-DSJ** [comment]
the specification for picture uploading page:

- [ ] the page should be able to choose pictures locally;
- [ ] only one picture is allowed to be uploaded and posted;
- [ ] there should be a text input box below for description of the picture;
- [ ] below the text input box, there should be a "submit" button to post the picture;
- [ ] the posted picture will be shown in the user's profile;
- [ ] other users should see these posted picture only by entering the user's profile;
- [ ] all posted pictures should be stored in mongoDB;
- [ ] after submit successfully, we should stay at the same page in case the user has another picture to post;
- [ ] there should be a "home" button to redirect to profile page;
- [ ] related CSS;

**Comment by successsb89** [comment]
done
