### ISSUE TITLE
Add section next to comment to record number of likes

### ISSUE THREAD

**Issue by kevinlizh1992** [yida-li/SOEN341#50]
There shall be an indication at the bottom of the picture indicating the total number of "likes"
#49

**Comment by Alex-DSJ** [comment]
yes, it's a good idea. we can have a new parameter "likeCounter" in the field "vibe" to track the number of people to has liked this vibe.

**Comment by successsb89** [comment]
Number of likes are presently counted and appeared. This idea is represented with "vibez" button instead of like button

**Comment by successsb89** [comment]
It is completely done with that way so I close this issue; this issue #50 has commited and referenced.

**Comment by Alex-DSJ** [comment]
[Acceptance Test](https://docs.google.com/spreadsheets/d/1CZK1ZZp62FcBFFwwg0ovlHvdOsHcdHgSov8aXYTdMAY/edit?usp=sharing) in row 16
