### ISSUE TITLE
The user should get a notification when someone comments on his/her posted picture

### ISSUE THREAD

**Issue by Alex-DSJ** [yida-li/SOEN341#52]
The user should get a notification when someone comments on his/her posted picture.

**Comment by Alex-DSJ** [comment]
if we comment on our own vibe, we should not recieve the notification.

**Comment by kennguyen0303** [comment]
They receive the notification. But the notification is not in real-time update (shows up right away without refreshing). Indeed, the notification only shows if the user refresh their dashboard

**Comment by Alex-DSJ** [comment]
> They receive the notification. But the notification is not in real-time update (shows up right away without refreshing). Indeed, the notification only shows if the user refresh their dashboard

I think it's enough for our present version, we can improve this function later if the user has such a requirement.

**Comment by Alex-DSJ** [comment]
[Acceptance Test](https://docs.google.com/spreadsheets/d/1CZK1ZZp62FcBFFwwg0ovlHvdOsHcdHgSov8aXYTdMAY/edit?usp=sharing) in row 19
