### ISSUE TITLE
The user should get  a notification when someone likes his/her vibe

### ISSUE THREAD

**Issue by Alex-DSJ** [yida-li/SOEN341#53]
The user should get  a notification when someone likes him/her, the signal should triggered when someone click the button "Like", after that, the button should be unavailable.

**Comment by successsb89** [comment]
additionally, "unlike" will remove notifications.

**Comment by successsb89** [comment]
if the user likes their own vibe, the user wont receive any notifications and if one user like someone's vibe by mistake and unlike it before that user login, then the other user will not receive a notification.

**Comment by Alex-DSJ** [comment]
[Acceptance Test](https://docs.google.com/spreadsheets/d/1CZK1ZZp62FcBFFwwg0ovlHvdOsHcdHgSov8aXYTdMAY/edit?usp=sharing) in row 20
