### ISSUE TITLE
The contents of the notification

### ISSUE THREAD

**Issue by Alex-DSJ** [yida-li/SOEN341#54]
The notification shoule be short and clear, we should only should "Who did what to whom", such as:
"Kevin has commented on your picture";
"Saebom has like you"

**Comment by successsb89** [comment]
As we discussed online, we also need to display how long ago this event happened. such as:
"Kevin has commented on your picture 5 minutes ago";

**Comment by successsb89** [comment]
now the notification shows all contents well.

**Comment by Alex-DSJ** [comment]
[Acceptance Test](https://docs.google.com/spreadsheets/d/1CZK1ZZp62FcBFFwwg0ovlHvdOsHcdHgSov8aXYTdMAY/edit?usp=sharing) in row 21
