### ISSUE TITLE
Where to find these notifications

### ISSUE THREAD

**Issue by Alex-DSJ** [yida-li/SOEN341#55]
We have to decide where to display these notifications and how them looks like.

**Comment by successsb89** [comment]
As discussed online, the notification icon will appear on the navbar after user login.

**Comment by kennguyen0303** [comment]
applied the feature. Can be closed now

**Comment by successsb89** [comment]
back end part of notification set up well, CSS part of that has to be added with more detail parts.

**Comment by kevinlizh1992** [comment]
alright guys, so I re-added the Navbar and buttons with material-UI

**Comment by Alex-DSJ** [comment]
[Acceptance Test](https://docs.google.com/spreadsheets/d/1CZK1ZZp62FcBFFwwg0ovlHvdOsHcdHgSov8aXYTdMAY/edit?usp=sharing) in row 19, 20
