### ISSUE TITLE
the UI of Newsfeed

### ISSUE THREAD

**Issue by Alex-DSJ** [yida-li/SOEN341#56]
we need a new page to show newsfeed information.
This page should be able to detect the user id and retrieve recent posted pictures with the descriptions and comments of his/her followers

**Comment by Alex-DSJ** [comment]
as discussion in discord, we decided to use the home page as the newsfeed page, which means the newsfeed page will show up once we login, and it will show all pictures of other "Vibers" in a descendent order of time. the appearance of each "vibe" will be the same as in profile page.

**Comment by successsb89** [comment]
Are we going to show user's profile next to the newsfeed? @kennguyen0303

**Comment by kennguyen0303** [comment]
It will break the architecture of the design, requires extra hours for re-designing. It is better like it now

**Comment by Alex-DSJ** [comment]
[Acceptance Test](https://docs.google.com/spreadsheets/d/1CZK1ZZp62FcBFFwwg0ovlHvdOsHcdHgSov8aXYTdMAY/edit?usp=sharing) in row 18
