### ISSUE TITLE
implementation of backend and database of newsfeed

### ISSUE THREAD

**Issue by Alex-DSJ** [yida-li/SOEN341#57]
the implementation of newsfeed backend with database should be similar with that of profile page, we need to delete the filter for profile which display user's own vibes, and re-organize the sequence of vibes.

**Comment by Alex-DSJ** [comment]
as discussed in discord, the "blocks" of newsfeed will be the same as our profile page, and since the "following" function is still unfinished, right now, we just display all "vibes" of other "vibers".

**Comment by kennguyen0303** [comment]
Will get back to this once the following feature is complete

**Comment by Alex-DSJ** [comment]
> Will get back to this once the following feature is complete

we have already finish this function, please refer this issue when you commit you new code.
