### ISSUE TITLE
scope of the newsfeed

### ISSUE THREAD

**Issue by Alex-DSJ** [yida-li/SOEN341#58]
Until what time, the pictures with their descriptions and comments should be available for newsfeed? couple of days? weeks? months? or all historical record?
From my perspective, we should keep this app light and quick response and avoid unnecessary functions, so we don't need display pictures long age. What about others?

**Comment by kennguyen0303** [comment]
It is better to only show the posts from the Vibers that the users is following. So, many irrelevant posts will be filtered out. 

Again, once following feature is complete, this issue will be reviewed
