### ISSUE TITLE
Problem with Database

### ISSUE THREAD

**Issue by yida-li** [yida-li/SOEN341#60]
as we all have agreed in the meeting today, there seems to be some major issues with the connections between our back-end and database so we will be integrating a new back end along with Firebase

**Comment by yida-li** [comment]
With the extra time provided, its critical that we integrate firebase as new database

**Comment by successsb89** [comment]
yes, we all agree with that opinion.

**Comment by successsb89** [comment]
we are using firebase now, close this issue
