### ISSUE TITLE
re-organize the folder to separate frontend to backend

### ISSUE THREAD

**Issue by Alex-DSJ** [yida-li/SOEN341#62]
transfer code for frontend and backend separately to have a better organization of folders and a better structure of the application

**Comment by successsb89** [comment]
Yes, I agree with you. How about that we are naming as "vibez-server" and "vibez-client"?

**Comment by Alex-DSJ** [comment]
this issue has been discussed online, and we decided to do it in this way mentioned by saebom: a "vibez-server" and a "vibez-client" folder.
