### ISSUE TITLE
travis-ci problem caused by re-organization

### ISSUE THREAD

**Issue by Alex-DSJ** [yida-li/SOEN341#63]
the problem caused by re-organization of folder and application need to be solved

**Comment by successsb89** [comment]
How about we are goint to upload "Vibez-client" file which is actually connected with hosting the browser? #kennguyen0303

**Comment by kennguyen0303** [comment]
Sounds like a good option. We will upload the front-end react code. Then, create a new repository for the backend. Then showing the link to the backend in the README of the frontend repo

**Comment by Alex-DSJ** [comment]
the problem of travis-ci has solved, it works automatically now.
