### ISSUE TITLE
resume for comment design matter

### ISSUE THREAD

**Issue by successsb89** [yida-li/SOEN341#66]
comment part has been implemented to back-end side respect with requirements. It will resume when front-end start in Sprint4.

integrate with issue #40

**Comment by successsb89** [comment]
I think that our comment part has been required all needs. What do you guys think? Do we need or functionalities for that?

**Comment by Alex-DSJ** [comment]
required all needs? satisfy all need : P
I think so, our comment system has satisfy all basic requirements of standard one.
as we discussed online, I have updated the detail of our comment system, you can check that issue and discuss more over there.
