### ISSUE TITLE
show the number of comments for each Vibe

### ISSUE THREAD

**Issue by Alex-DSJ** [yida-li/SOEN341#68]
a subissue of #15 
display how many viber has commented on this vibe.
we need to store this information in our database and operate it properly.

**Comment by kennguyen0303** [comment]
I check and the back end works. The front end does not show the update right away since it does not get the new state (set_state action is not called). Trying to fix

**Comment by kevinlizh1992** [comment]
Alright added the like and comment system, it also now displays the # of comments/likes, works well with DB

**Comment by Alex-DSJ** [comment]
[Acceptance Test](https://docs.google.com/spreadsheets/d/1CZK1ZZp62FcBFFwwg0ovlHvdOsHcdHgSov8aXYTdMAY/edit?usp=sharing) in row 16
