### ISSUE TITLE
restrict the comment on vibe only

### ISSUE THREAD

**Issue by Alex-DSJ** [yida-li/SOEN341#69]
we dont offer the function of "comment on comment", so we need to check our code if there is possible way for commenting on others comments.

**Comment by successsb89** [comment]
until now we can only comment on vibez not the comment on comment

**Comment by Alex-DSJ** [comment]
[Acceptance Test](https://docs.google.com/spreadsheets/d/1CZK1ZZp62FcBFFwwg0ovlHvdOsHcdHgSov8aXYTdMAY/edit?usp=sharing) in row 17
