### ISSUE TITLE
core feature 3: leaving comments on posted pictures

### ISSUE THREAD

**Issue by Alex-DSJ** [yida-li/SOEN341#7]
the third core feature required by our customer is that users can leave comments on posted pictures.

**Comment by yida-li** [comment]
One thing to be taken in consideration is the maximum amount of words possible in 1 comment

**Comment by Alex-DSJ** [comment]
I agree with you, but will it limited by the number of characters will be more practical?
By the way, for the comment, I think users should be able to post a comment whenever they see the picture, either on the profile, or on the news feed.

**Comment by yida-li** [comment]
> I agree with you, but will it limited by the number of characters will be more practical?
> By the way, for the comment, I think users should be able to post a comment whenever they see the picture, either on the profile, or on the news feed.

you're right, let's set an upper limit of 200 characters per comment.

**Comment by yida-li** [comment]
another pertinent user story might involves a user wanting delete/remove their comments.

**Comment by yida-li** [comment]
comments are posted in a chronological order, which is seemingly pretty simple to implement

**Comment by Alex-DSJ** [comment]
specifications for this story:

- [ ] everyone should be able to comment on anyone's pictures;
- [ ] commnets should be limited within 200 characters(length can be discussed later);
- [ ] comments shoule be displayed below the target picture;
- [ ] comments should be displayed in reverse chronological order;
- [ ] users should only be allowed to comment on the picture, commenting on others is not allowed;
- [ ] related CSS

**Comment by successsb89** [comment]
this issue is specified with more details with other issues number. (repeated)
